export const BOOKS_ACTIONS = {
    GET_ALL_BOOKS: 'GET_ALL_BOOKS',
    GET_ALL_BOOKS_SUCCESS: 'GET_ALL_BOOKS_SUCCESS',
    POST_BOOK_REQUEST: 'POST_BOOK_REQUEST',
    POST_BOOK_SUCCESS: 'POST_BOOK_SUCCESS',
    POST_BOOK_FAILED: 'POST_BOOK_FAILED',
} as const;
